#ifndef TC_COLOR_H
#define TC_COLOR_H

enum TCColor { TC_COLOR_BLACK, TC_COLOR_RED, TC_COLOR_GREEN, TC_COLOR_YELLOW, TC_COLOR_BLUE, TC_COLOR_MAGENTA, TC_COLOR_CYAN, TC_COLOR_WHITE, TC_COLOR_DEFAULT };

#endif
